with-expecter: true
quiet: false
filename: "mock_{{.InterfaceName}}_test.go"
mockname: "Mock{{.InterfaceName}}"
inpackage: true

packages:
  service-currency/internal:
    config:
      all: true
      recursive: true