// Code generated by mockery v2.53.5. DO NOT EDIT.

package internal

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAuditLogStorage is an autogenerated mock type for the AuditLogStorage type
type MockAuditLogStorage struct {
	mock.Mock
}

type MockAuditLogStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLogStorage) EXPECT() *MockAuditLogStorage_Expecter {
	return &MockAuditLogStorage_Expecter{mock: &_m.Mock}
}

// Insert provides a mock function with given fields: ctx, path, status, dateAsOf
func (_m *MockAuditLogStorage) Insert(ctx context.Context, path string, status *int, dateAsOf *Date) error {
	ret := _m.Called(ctx, path, status, dateAsOf)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *int, *Date) error); ok {
		r0 = rf(ctx, path, status, dateAsOf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditLogStorage_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockAuditLogStorage_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - status *int
//   - dateAsOf *Date
func (_e *MockAuditLogStorage_Expecter) Insert(ctx interface{}, path interface{}, status interface{}, dateAsOf interface{}) *MockAuditLogStorage_Insert_Call {
	return &MockAuditLogStorage_Insert_Call{Call: _e.mock.On("Insert", ctx, path, status, dateAsOf)}
}

func (_c *MockAuditLogStorage_Insert_Call) Run(run func(ctx context.Context, path string, status *int, dateAsOf *Date)) *MockAuditLogStorage_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*int), args[3].(*Date))
	})
	return _c
}

func (_c *MockAuditLogStorage_Insert_Call) Return(_a0 error) *MockAuditLogStorage_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditLogStorage_Insert_Call) RunAndReturn(run func(context.Context, string, *int, *Date) error) *MockAuditLogStorage_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditLogStorage creates a new instance of MockAuditLogStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLogStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLogStorage {
	mock := &MockAuditLogStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
