// Code generated by mockery v2.53.5. DO NOT EDIT.

package internal

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRatesClient is an autogenerated mock type for the RatesClient type
type MockRatesClient struct {
	mock.Mock
}

type MockRatesClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRatesClient) EXPECT() *MockRatesClient_Expecter {
	return &MockRatesClient_Expecter{mock: &_m.Mock}
}

// HistoricalRates provides a mock function with given fields: ctx, date, base, symbols
func (_m *MockRatesClient) HistoricalRates(ctx context.Context, date Date, base CurrencyCode, symbols []CurrencyCode) (*LatestRatesResponse, error) {
	ret := _m.Called(ctx, date, base, symbols)

	if len(ret) == 0 {
		panic("no return value specified for HistoricalRates")
	}

	var r0 *LatestRatesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, Date, CurrencyCode, []CurrencyCode) (*LatestRatesResponse, error)); ok {
		return rf(ctx, date, base, symbols)
	}
	if rf, ok := ret.Get(0).(func(context.Context, Date, CurrencyCode, []CurrencyCode) *LatestRatesResponse); ok {
		r0 = rf(ctx, date, base, symbols)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*LatestRatesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, Date, CurrencyCode, []CurrencyCode) error); ok {
		r1 = rf(ctx, date, base, symbols)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRatesClient_HistoricalRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HistoricalRates'
type MockRatesClient_HistoricalRates_Call struct {
	*mock.Call
}

// HistoricalRates is a helper method to define mock.On call
//   - ctx context.Context
//   - date Date
//   - base CurrencyCode
//   - symbols []CurrencyCode
func (_e *MockRatesClient_Expecter) HistoricalRates(ctx interface{}, date interface{}, base interface{}, symbols interface{}) *MockRatesClient_HistoricalRates_Call {
	return &MockRatesClient_HistoricalRates_Call{Call: _e.mock.On("HistoricalRates", ctx, date, base, symbols)}
}

func (_c *MockRatesClient_HistoricalRates_Call) Run(run func(ctx context.Context, date Date, base CurrencyCode, symbols []CurrencyCode)) *MockRatesClient_HistoricalRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(Date), args[2].(CurrencyCode), args[3].([]CurrencyCode))
	})
	return _c
}

func (_c *MockRatesClient_HistoricalRates_Call) Return(_a0 *LatestRatesResponse, _a1 error) *MockRatesClient_HistoricalRates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRatesClient_HistoricalRates_Call) RunAndReturn(run func(context.Context, Date, CurrencyCode, []CurrencyCode) (*LatestRatesResponse, error)) *MockRatesClient_HistoricalRates_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRatesClient creates a new instance of MockRatesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRatesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRatesClient {
	mock := &MockRatesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
