// Code generated by mockery v2.53.5. DO NOT EDIT.

package internal

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRequestAuditLogger is an autogenerated mock type for the RequestAuditLogger type
type MockRequestAuditLogger struct {
	mock.Mock
}

type MockRequestAuditLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestAuditLogger) EXPECT() *MockRequestAuditLogger_Expecter {
	return &MockRequestAuditLogger_Expecter{mock: &_m.Mock}
}

// LogRequest provides a mock function with given fields: ctx, path, status, dateAsOf
func (_m *MockRequestAuditLogger) LogRequest(ctx context.Context, path string, status *int, dateAsOf *Date) error {
	ret := _m.Called(ctx, path, status, dateAsOf)

	if len(ret) == 0 {
		panic("no return value specified for LogRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *int, *Date) error); ok {
		r0 = rf(ctx, path, status, dateAsOf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRequestAuditLogger_LogRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogRequest'
type MockRequestAuditLogger_LogRequest_Call struct {
	*mock.Call
}

// LogRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - status *int
//   - dateAsOf *Date
func (_e *MockRequestAuditLogger_Expecter) LogRequest(ctx interface{}, path interface{}, status interface{}, dateAsOf interface{}) *MockRequestAuditLogger_LogRequest_Call {
	return &MockRequestAuditLogger_LogRequest_Call{Call: _e.mock.On("LogRequest", ctx, path, status, dateAsOf)}
}

func (_c *MockRequestAuditLogger_LogRequest_Call) Run(run func(ctx context.Context, path string, status *int, dateAsOf *Date)) *MockRequestAuditLogger_LogRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*int), args[3].(*Date))
	})
	return _c
}

func (_c *MockRequestAuditLogger_LogRequest_Call) Return(_a0 error) *MockRequestAuditLogger_LogRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRequestAuditLogger_LogRequest_Call) RunAndReturn(run func(context.Context, string, *int, *Date) error) *MockRequestAuditLogger_LogRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRequestAuditLogger creates a new instance of MockRequestAuditLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestAuditLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestAuditLogger {
	mock := &MockRequestAuditLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
