// Code generated by mockery v2.53.5. DO NOT EDIT.

package internal

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAPIKeyRepository is an autogenerated mock type for the APIKeyRepository type
type MockAPIKeyRepository struct {
	mock.Mock
}

type MockAPIKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyRepository) EXPECT() *MockAPIKeyRepository_Expecter {
	return &MockAPIKeyRepository_Expecter{mock: &_m.Mock}
}

// GetStatusByHash provides a mock function with given fields: ctx, keyHash
func (_m *MockAPIKeyRepository) GetStatusByHash(ctx context.Context, keyHash string) (bool, bool, error) {
	ret := _m.Called(ctx, keyHash)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusByHash")
	}

	var r0 bool
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, bool, error)); ok {
		return rf(ctx, keyHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, keyHash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, keyHash)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, keyHash)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAPIKeyRepository_GetStatusByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatusByHash'
type MockAPIKeyRepository_GetStatusByHash_Call struct {
	*mock.Call
}

// GetStatusByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - keyHash string
func (_e *MockAPIKeyRepository_Expecter) GetStatusByHash(ctx interface{}, keyHash interface{}) *MockAPIKeyRepository_GetStatusByHash_Call {
	return &MockAPIKeyRepository_GetStatusByHash_Call{Call: _e.mock.On("GetStatusByHash", ctx, keyHash)}
}

func (_c *MockAPIKeyRepository_GetStatusByHash_Call) Run(run func(ctx context.Context, keyHash string)) *MockAPIKeyRepository_GetStatusByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPIKeyRepository_GetStatusByHash_Call) Return(exists bool, isActive bool, err error) *MockAPIKeyRepository_GetStatusByHash_Call {
	_c.Call.Return(exists, isActive, err)
	return _c
}

func (_c *MockAPIKeyRepository_GetStatusByHash_Call) RunAndReturn(run func(context.Context, string) (bool, bool, error)) *MockAPIKeyRepository_GetStatusByHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAPIKeyRepository creates a new instance of MockAPIKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyRepository {
	mock := &MockAPIKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
