// Code generated by mockery v2.53.5. DO NOT EDIT.

package currencyFreaks

import (
	context "context"
	internal "service-currency/internal"

	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"
)

// MockRatesStorage is an autogenerated mock type for the RatesStorage type
type MockRatesStorage struct {
	mock.Mock
}

type MockRatesStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRatesStorage) EXPECT() *MockRatesStorage_Expecter {
	return &MockRatesStorage_Expecter{mock: &_m.Mock}
}

// UpsertRatesMap provides a mock function with given fields: ctx, base, asOfDate, rates
func (_m *MockRatesStorage) UpsertRatesMap(ctx context.Context, base internal.CurrencyCode, asOfDate internal.Date, rates map[internal.CurrencyCode]decimal.Decimal) error {
	ret := _m.Called(ctx, base, asOfDate, rates)

	if len(ret) == 0 {
		panic("no return value specified for UpsertRatesMap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, internal.CurrencyCode, internal.Date, map[internal.CurrencyCode]decimal.Decimal) error); ok {
		r0 = rf(ctx, base, asOfDate, rates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRatesStorage_UpsertRatesMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertRatesMap'
type MockRatesStorage_UpsertRatesMap_Call struct {
	*mock.Call
}

// UpsertRatesMap is a helper method to define mock.On call
//   - ctx context.Context
//   - base internal.CurrencyCode
//   - asOfDate internal.Date
//   - rates map[internal.CurrencyCode]decimal.Decimal
func (_e *MockRatesStorage_Expecter) UpsertRatesMap(ctx interface{}, base interface{}, asOfDate interface{}, rates interface{}) *MockRatesStorage_UpsertRatesMap_Call {
	return &MockRatesStorage_UpsertRatesMap_Call{Call: _e.mock.On("UpsertRatesMap", ctx, base, asOfDate, rates)}
}

func (_c *MockRatesStorage_UpsertRatesMap_Call) Run(run func(ctx context.Context, base internal.CurrencyCode, asOfDate internal.Date, rates map[internal.CurrencyCode]decimal.Decimal)) *MockRatesStorage_UpsertRatesMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(internal.CurrencyCode), args[2].(internal.Date), args[3].(map[internal.CurrencyCode]decimal.Decimal))
	})
	return _c
}

func (_c *MockRatesStorage_UpsertRatesMap_Call) Return(_a0 error) *MockRatesStorage_UpsertRatesMap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRatesStorage_UpsertRatesMap_Call) RunAndReturn(run func(context.Context, internal.CurrencyCode, internal.Date, map[internal.CurrencyCode]decimal.Decimal) error) *MockRatesStorage_UpsertRatesMap_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRatesStorage creates a new instance of MockRatesStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRatesStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRatesStorage {
	mock := &MockRatesStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
