// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAPIKeyValidator is an autogenerated mock type for the APIKeyValidator type
type MockAPIKeyValidator struct {
	mock.Mock
}

type MockAPIKeyValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyValidator) EXPECT() *MockAPIKeyValidator_Expecter {
	return &MockAPIKeyValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with given fields: ctx, rawKey
func (_m *MockAPIKeyValidator) Validate(ctx context.Context, rawKey string) (bool, bool, error) {
	ret := _m.Called(ctx, rawKey)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 bool
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, bool, error)); ok {
		return rf(ctx, rawKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, rawKey)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, rawKey)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, rawKey)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAPIKeyValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockAPIKeyValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - rawKey string
func (_e *MockAPIKeyValidator_Expecter) Validate(ctx interface{}, rawKey interface{}) *MockAPIKeyValidator_Validate_Call {
	return &MockAPIKeyValidator_Validate_Call{Call: _e.mock.On("Validate", ctx, rawKey)}
}

func (_c *MockAPIKeyValidator_Validate_Call) Run(run func(ctx context.Context, rawKey string)) *MockAPIKeyValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPIKeyValidator_Validate_Call) Return(exists bool, isActive bool, err error) *MockAPIKeyValidator_Validate_Call {
	_c.Call.Return(exists, isActive, err)
	return _c
}

func (_c *MockAPIKeyValidator_Validate_Call) RunAndReturn(run func(context.Context, string) (bool, bool, error)) *MockAPIKeyValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAPIKeyValidator creates a new instance of MockAPIKeyValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyValidator {
	mock := &MockAPIKeyValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
