// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock

import (
	context "context"
	internal "service-currency/internal"
	currencyFreaks "service-currency/internal/currency_freaks"

	mock "github.com/stretchr/testify/mock"
)

// MockRatesClient is an autogenerated mock type for the RatesClient type
type MockRatesClient struct {
	mock.Mock
}

type MockRatesClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRatesClient) EXPECT() *MockRatesClient_Expecter {
	return &MockRatesClient_Expecter{mock: &_m.Mock}
}

// FetchAndSaveLatest provides a mock function with given fields: ctx, storage, base, symbols
func (_m *MockRatesClient) FetchAndSaveLatest(ctx context.Context, storage currencyFreaks.RatesStorage, base internal.CurrencyCode, symbols []internal.CurrencyCode) (*internal.LatestRatesResponse, error) {
	ret := _m.Called(ctx, storage, base, symbols)

	if len(ret) == 0 {
		panic("no return value specified for FetchAndSaveLatest")
	}

	var r0 *internal.LatestRatesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, currencyFreaks.RatesStorage, internal.CurrencyCode, []internal.CurrencyCode) (*internal.LatestRatesResponse, error)); ok {
		return rf(ctx, storage, base, symbols)
	}
	if rf, ok := ret.Get(0).(func(context.Context, currencyFreaks.RatesStorage, internal.CurrencyCode, []internal.CurrencyCode) *internal.LatestRatesResponse); ok {
		r0 = rf(ctx, storage, base, symbols)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.LatestRatesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, currencyFreaks.RatesStorage, internal.CurrencyCode, []internal.CurrencyCode) error); ok {
		r1 = rf(ctx, storage, base, symbols)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRatesClient_FetchAndSaveLatest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAndSaveLatest'
type MockRatesClient_FetchAndSaveLatest_Call struct {
	*mock.Call
}

// FetchAndSaveLatest is a helper method to define mock.On call
//   - ctx context.Context
//   - storage currencyFreaks.RatesStorage
//   - base internal.CurrencyCode
//   - symbols []internal.CurrencyCode
func (_e *MockRatesClient_Expecter) FetchAndSaveLatest(ctx interface{}, storage interface{}, base interface{}, symbols interface{}) *MockRatesClient_FetchAndSaveLatest_Call {
	return &MockRatesClient_FetchAndSaveLatest_Call{Call: _e.mock.On("FetchAndSaveLatest", ctx, storage, base, symbols)}
}

func (_c *MockRatesClient_FetchAndSaveLatest_Call) Run(run func(ctx context.Context, storage currencyFreaks.RatesStorage, base internal.CurrencyCode, symbols []internal.CurrencyCode)) *MockRatesClient_FetchAndSaveLatest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(currencyFreaks.RatesStorage), args[2].(internal.CurrencyCode), args[3].([]internal.CurrencyCode))
	})
	return _c
}

func (_c *MockRatesClient_FetchAndSaveLatest_Call) Return(_a0 *internal.LatestRatesResponse, _a1 error) *MockRatesClient_FetchAndSaveLatest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRatesClient_FetchAndSaveLatest_Call) RunAndReturn(run func(context.Context, currencyFreaks.RatesStorage, internal.CurrencyCode, []internal.CurrencyCode) (*internal.LatestRatesResponse, error)) *MockRatesClient_FetchAndSaveLatest_Call {
	_c.Call.Return(run)
	return _c
}

// HistoricalRates provides a mock function with given fields: ctx, date, base, symbols
func (_m *MockRatesClient) HistoricalRates(ctx context.Context, date internal.Date, base internal.CurrencyCode, symbols []internal.CurrencyCode) (*internal.LatestRatesResponse, error) {
	ret := _m.Called(ctx, date, base, symbols)

	if len(ret) == 0 {
		panic("no return value specified for HistoricalRates")
	}

	var r0 *internal.LatestRatesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, internal.Date, internal.CurrencyCode, []internal.CurrencyCode) (*internal.LatestRatesResponse, error)); ok {
		return rf(ctx, date, base, symbols)
	}
	if rf, ok := ret.Get(0).(func(context.Context, internal.Date, internal.CurrencyCode, []internal.CurrencyCode) *internal.LatestRatesResponse); ok {
		r0 = rf(ctx, date, base, symbols)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.LatestRatesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, internal.Date, internal.CurrencyCode, []internal.CurrencyCode) error); ok {
		r1 = rf(ctx, date, base, symbols)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRatesClient_HistoricalRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HistoricalRates'
type MockRatesClient_HistoricalRates_Call struct {
	*mock.Call
}

// HistoricalRates is a helper method to define mock.On call
//   - ctx context.Context
//   - date internal.Date
//   - base internal.CurrencyCode
//   - symbols []internal.CurrencyCode
func (_e *MockRatesClient_Expecter) HistoricalRates(ctx interface{}, date interface{}, base interface{}, symbols interface{}) *MockRatesClient_HistoricalRates_Call {
	return &MockRatesClient_HistoricalRates_Call{Call: _e.mock.On("HistoricalRates", ctx, date, base, symbols)}
}

func (_c *MockRatesClient_HistoricalRates_Call) Run(run func(ctx context.Context, date internal.Date, base internal.CurrencyCode, symbols []internal.CurrencyCode)) *MockRatesClient_HistoricalRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(internal.Date), args[2].(internal.CurrencyCode), args[3].([]internal.CurrencyCode))
	})
	return _c
}

func (_c *MockRatesClient_HistoricalRates_Call) Return(_a0 *internal.LatestRatesResponse, _a1 error) *MockRatesClient_HistoricalRates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRatesClient_HistoricalRates_Call) RunAndReturn(run func(context.Context, internal.Date, internal.CurrencyCode, []internal.CurrencyCode) (*internal.LatestRatesResponse, error)) *MockRatesClient_HistoricalRates_Call {
	_c.Call.Return(run)
	return _c
}

// LatestRates provides a mock function with given fields: ctx, base, symbols
func (_m *MockRatesClient) LatestRates(ctx context.Context, base internal.CurrencyCode, symbols []internal.CurrencyCode) (*internal.LatestRatesResponse, error) {
	ret := _m.Called(ctx, base, symbols)

	if len(ret) == 0 {
		panic("no return value specified for LatestRates")
	}

	var r0 *internal.LatestRatesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, internal.CurrencyCode, []internal.CurrencyCode) (*internal.LatestRatesResponse, error)); ok {
		return rf(ctx, base, symbols)
	}
	if rf, ok := ret.Get(0).(func(context.Context, internal.CurrencyCode, []internal.CurrencyCode) *internal.LatestRatesResponse); ok {
		r0 = rf(ctx, base, symbols)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.LatestRatesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, internal.CurrencyCode, []internal.CurrencyCode) error); ok {
		r1 = rf(ctx, base, symbols)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRatesClient_LatestRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestRates'
type MockRatesClient_LatestRates_Call struct {
	*mock.Call
}

// LatestRates is a helper method to define mock.On call
//   - ctx context.Context
//   - base internal.CurrencyCode
//   - symbols []internal.CurrencyCode
func (_e *MockRatesClient_Expecter) LatestRates(ctx interface{}, base interface{}, symbols interface{}) *MockRatesClient_LatestRates_Call {
	return &MockRatesClient_LatestRates_Call{Call: _e.mock.On("LatestRates", ctx, base, symbols)}
}

func (_c *MockRatesClient_LatestRates_Call) Run(run func(ctx context.Context, base internal.CurrencyCode, symbols []internal.CurrencyCode)) *MockRatesClient_LatestRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(internal.CurrencyCode), args[2].([]internal.CurrencyCode))
	})
	return _c
}

func (_c *MockRatesClient_LatestRates_Call) Return(_a0 *internal.LatestRatesResponse, _a1 error) *MockRatesClient_LatestRates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRatesClient_LatestRates_Call) RunAndReturn(run func(context.Context, internal.CurrencyCode, []internal.CurrencyCode) (*internal.LatestRatesResponse, error)) *MockRatesClient_LatestRates_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRatesClient creates a new instance of MockRatesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRatesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRatesClient {
	mock := &MockRatesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
