// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock

import (
	context "context"
	internal "service-currency/internal"

	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// GetLatest provides a mock function with given fields: ctx, base, quotes
func (_m *MockStorage) GetLatest(ctx context.Context, base internal.CurrencyCode, quotes []internal.CurrencyCode) ([]internal.CurrencyLatestRate, error) {
	ret := _m.Called(ctx, base, quotes)

	if len(ret) == 0 {
		panic("no return value specified for GetLatest")
	}

	var r0 []internal.CurrencyLatestRate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, internal.CurrencyCode, []internal.CurrencyCode) ([]internal.CurrencyLatestRate, error)); ok {
		return rf(ctx, base, quotes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, internal.CurrencyCode, []internal.CurrencyCode) []internal.CurrencyLatestRate); ok {
		r0 = rf(ctx, base, quotes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]internal.CurrencyLatestRate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, internal.CurrencyCode, []internal.CurrencyCode) error); ok {
		r1 = rf(ctx, base, quotes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetLatest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatest'
type MockStorage_GetLatest_Call struct {
	*mock.Call
}

// GetLatest is a helper method to define mock.On call
//   - ctx context.Context
//   - base internal.CurrencyCode
//   - quotes []internal.CurrencyCode
func (_e *MockStorage_Expecter) GetLatest(ctx interface{}, base interface{}, quotes interface{}) *MockStorage_GetLatest_Call {
	return &MockStorage_GetLatest_Call{Call: _e.mock.On("GetLatest", ctx, base, quotes)}
}

func (_c *MockStorage_GetLatest_Call) Run(run func(ctx context.Context, base internal.CurrencyCode, quotes []internal.CurrencyCode)) *MockStorage_GetLatest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(internal.CurrencyCode), args[2].([]internal.CurrencyCode))
	})
	return _c
}

func (_c *MockStorage_GetLatest_Call) Return(_a0 []internal.CurrencyLatestRate, _a1 error) *MockStorage_GetLatest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetLatest_Call) RunAndReturn(run func(context.Context, internal.CurrencyCode, []internal.CurrencyCode) ([]internal.CurrencyLatestRate, error)) *MockStorage_GetLatest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
